//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1TC3J13;Initial Catalog=Dissertation_Management;Integrated Se" +
            "curity=True")]
        public string Dissertation_ManagementConnectionString {
            get {
                return ((string)(this["Dissertation_ManagementConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1TC3J13;Initial Catalog=Thesis_mamagement;Integrated Security" +
<<<<<<< HEAD
<<<<<<< HEAD
            "=True;Encrypt=True;TrustServerCertificate=True")]
=======
            "=True;TrustServerCertificate=True")]
>>>>>>> e1c60e7bc1db901804d87489331aa0e4cf8ab45a
=======
            "=True;TrustServerCertificate=True")]
>>>>>>> e1c60e7bc1db901804d87489331aa0e4cf8ab45a
        public string Thesis_mamagementConnectionString {
            get {
                return ((string)(this["Thesis_mamagementConnectionString"]));
            }
        }
    }
}
